### ISSUE TITLE
Mojave local build fails due to missing libsdl2 sources

### ISSUE THREAD

**Issue by Random-Scientist** [GabLeRoux/macos-crossover-cloud-build#31]
I got it to build after removing --with-sdl from the buildscript, I think it needs to pull the sources from [here](https://www.libsdl.org/download-2.0.php) and link them properly.

**Comment by Gcenx** [comment]
The issue is `brew` only supports the versions of macOS that Apple supports.

This project builds `wine64` & `wine32on64` targets as those work on macOS Catalina and later and only require `x86_64` libraries where wine requires `i386` libraries (`brew` doesn’t provide `i386` libraries)

As your still running macOS Mojave you could simply use upstream Winehq packages, I’m one of the official Winehq package maintainers for macOS and those run on macOS High Sierra and later and include `wine` & `wine64`.

I personally don’t want to work on getting this to function on versions of macOS that `brew` no longer support, if @dasmy &/or @GabLeRoux wanted to work on that is another matter.

**Comment by dasmy** [comment]
> The issue is `brew` only supports the versions of macOS that Apple supports.
> 
> This project builds `wine64` & `wine32on64` targets as those work on macOS Catalina and later and only require `x86_64` libraries where wine requires `i386` libraries (`brew` doesn’t provide `i386` libraries)
> 
> As your still running macOS Mojave you could simply use upstream Winehq packages, I’m one of the official Winehq package maintainers for macOS and those run on macOS High Sierra and later and include `wine` & `wine64`.
> 
> I personally don’t want to work on getting this to function on versions of macOS that `brew` no longer support, if @dasmy &/or @GabLeRoux wanted to work on that is another matter.

I am also not very inclined to work on Mojave compatibility as I do not have a Mojave machine myself any more. The whole point behind wine32on64 is the missing support for executing 32bit code "natively" on later macOS versions.

**Comment by Random-Scientist** [comment]
Understood. That resolves the issue :) I'll submit a PR if I ever find a fix.

**Comment by Gcenx** [comment]
@The-Minecraft-Scientist it would take a rather massive overhaul to this project to enable compiling for `i386` along with compiling the required `i386` libraries.

My Intel Macbook Pro is still on macOS Mojave with Macports where I first modify `/opt/local/etc/macports/macports.conf`
```
macosx_deployment_target     10.13
macosx_sdk_version           10.13
```
Along with `/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk`

Also needed edits `/opt/local/etc/macports/sources.conf`
```
file:///Users/gcenx/ports [nosync]
file:///opt/macports-legacy_rust
file:///opt/macports-gstreamer1
file:///opt/macports-wine
rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]
```
Each contain multiple overrides to macports behaviour `ports` alone contains 72 overriders, all of this is _easier_ then manually compiling everything needed from source.
